export { default as ContextMenu } from './components/ContextMenu/ContextMenu.vue'
export { registerComponentMenu } from './util/registerComponentMenu'
export * from './types/menu'
export type { ContextMenuProps } from './components/ContextMenu/types'
// 样式可选引入：import 'vue-rightclick-menu/styles/context-menu.css'
